// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class HSSOktaNativeAuthRequest {
  HSSOktaNativeAuthRequest({
    required this.username,
    required this.password,
  });

  String username;

  String password;

  Object encode() {
    return <Object?>[
      username,
      password,
    ];
  }

  static HSSOktaNativeAuthRequest decode(Object result) {
    result as List<Object?>;
    return HSSOktaNativeAuthRequest(
      username: result[0]! as String,
      password: result[1]! as String,
    );
  }
}

class HSSOktaNativeAuthResult {
  HSSOktaNativeAuthResult({
    required this.result,
  });

  String result;

  Object encode() {
    return <Object?>[
      result,
    ];
  }

  static HSSOktaNativeAuthResult decode(Object result) {
    result as List<Object?>;
    return HSSOktaNativeAuthResult(
      result: result[0]! as String,
    );
  }
}

class _DirectAuthAPICodec extends StandardMessageCodec {
  const _DirectAuthAPICodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is HSSOktaNativeAuthRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is HSSOktaNativeAuthResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return HSSOktaNativeAuthRequest.decode(readValue(buffer)!);
      case 129:
        return HSSOktaNativeAuthResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DirectAuthAPI {
  /// Constructor for [DirectAuthAPI].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DirectAuthAPI({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _DirectAuthAPICodec();

  Future<HSSOktaNativeAuthResult> signInWithCredentials(
      HSSOktaNativeAuthRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.hss_okta_flutter.DirectAuthAPI.signInWithCredentials',
        codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as HSSOktaNativeAuthResult?)!;
    }
  }
}
