// Autogenerated from Pigeon (v18.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum AuthenticationType: Int {
  case browser = 0
  case sso = 1
  case directAuth = 2
}

enum DirectAuthenticationResult: Int {
  case success = 0
  case mfaRequired = 1
  case error = 2
}

enum AuthenticationFactor: Int {
  case otp = 0
  case oob = 1
}

enum RequestIntent: Int {
  case enrollNewUser = 0
  case login = 1
  case credentialEnrollment = 2
  case credentialUnenrollment = 3
  case credentialRecovery = 4
  case credentialModify = 5
  case unknown = 6
}

/// Generated class from Pigeon that represents data sent in messages.
struct AuthenticationResult {
  var result: DirectAuthenticationResult? = nil
  var error: String? = nil
  var token: OktaToken? = nil
  var userInfo: UserInfo? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> AuthenticationResult? {
    var result: DirectAuthenticationResult? = nil
    let resultEnumVal: Int? = nilOrValue(__pigeon_list[0])
    if let resultRawValue = resultEnumVal {
      result = DirectAuthenticationResult(rawValue: resultRawValue)!
    }
    let error: String? = nilOrValue(__pigeon_list[1])
    let token: OktaToken? = nilOrValue(__pigeon_list[2])
    let userInfo: UserInfo? = nilOrValue(__pigeon_list[3])

    return AuthenticationResult(
      result: result,
      error: error,
      token: token,
      userInfo: userInfo
    )
  }
  func toList() -> [Any?] {
    return [
      result?.rawValue,
      error,
      token,
      userInfo,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OktaToken {
  var id: String? = nil
  var token: String? = nil
  var issuedAt: Int64? = nil
  var tokenType: String? = nil
  var accessToken: String? = nil
  var scope: String? = nil
  var refreshToken: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> OktaToken? {
    let id: String? = nilOrValue(__pigeon_list[0])
    let token: String? = nilOrValue(__pigeon_list[1])
    let issuedAt: Int64? = isNullish(__pigeon_list[2]) ? nil : (__pigeon_list[2] is Int64? ? __pigeon_list[2] as! Int64? : Int64(__pigeon_list[2] as! Int32))
    let tokenType: String? = nilOrValue(__pigeon_list[3])
    let accessToken: String? = nilOrValue(__pigeon_list[4])
    let scope: String? = nilOrValue(__pigeon_list[5])
    let refreshToken: String? = nilOrValue(__pigeon_list[6])

    return OktaToken(
      id: id,
      token: token,
      issuedAt: issuedAt,
      tokenType: tokenType,
      accessToken: accessToken,
      scope: scope,
      refreshToken: refreshToken
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      token,
      issuedAt,
      tokenType,
      accessToken,
      scope,
      refreshToken,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UserInfo {
  var userId: String
  var givenName: String
  var middleName: String
  var familyName: String
  var gender: String
  var email: String
  var phoneNumber: String
  var username: String

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> UserInfo? {
    let userId = __pigeon_list[0] as! String
    let givenName = __pigeon_list[1] as! String
    let middleName = __pigeon_list[2] as! String
    let familyName = __pigeon_list[3] as! String
    let gender = __pigeon_list[4] as! String
    let email = __pigeon_list[5] as! String
    let phoneNumber = __pigeon_list[6] as! String
    let username = __pigeon_list[7] as! String

    return UserInfo(
      userId: userId,
      givenName: givenName,
      middleName: middleName,
      familyName: familyName,
      gender: gender,
      email: email,
      phoneNumber: phoneNumber,
      username: username
    )
  }
  func toList() -> [Any?] {
    return [
      userId,
      givenName,
      middleName,
      familyName,
      gender,
      email,
      phoneNumber,
      username,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DirectAuthRequest {
  var username: String
  var password: String
  var factors: [String?]

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> DirectAuthRequest? {
    let username = __pigeon_list[0] as! String
    let password = __pigeon_list[1] as! String
    let factors = __pigeon_list[2] as! [String?]

    return DirectAuthRequest(
      username: username,
      password: password,
      factors: factors
    )
  }
  func toList() -> [Any?] {
    return [
      username,
      password,
      factors,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeviceAuthorizationSession {
  var userCode: String? = nil
  var verificationUri: String? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> DeviceAuthorizationSession? {
    let userCode: String? = nilOrValue(__pigeon_list[0])
    let verificationUri: String? = nilOrValue(__pigeon_list[1])

    return DeviceAuthorizationSession(
      userCode: userCode,
      verificationUri: verificationUri
    )
  }
  func toList() -> [Any?] {
    return [
      userCode,
      verificationUri,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct IdxResponse {
  var expiresAt: Int64? = nil
  var user: UserInfo? = nil
  var canCancel: Bool
  var isLoginSuccessful: Bool
  var intent: RequestIntent
  var messages: [String?]
  var remediations: [String?]? = nil
  var authenticators: [String?]? = nil
  var token: OktaToken? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ __pigeon_list: [Any?]) -> IdxResponse? {
    let expiresAt: Int64? = isNullish(__pigeon_list[0]) ? nil : (__pigeon_list[0] is Int64? ? __pigeon_list[0] as! Int64? : Int64(__pigeon_list[0] as! Int32))
    let user: UserInfo? = nilOrValue(__pigeon_list[1])
    let canCancel = __pigeon_list[2] as! Bool
    let isLoginSuccessful = __pigeon_list[3] as! Bool
    let intent = RequestIntent(rawValue: __pigeon_list[4] as! Int)!
    let messages = __pigeon_list[5] as! [String?]
    let remediations: [String?]? = nilOrValue(__pigeon_list[6])
    let authenticators: [String?]? = nilOrValue(__pigeon_list[7])
    let token: OktaToken? = nilOrValue(__pigeon_list[8])

    return IdxResponse(
      expiresAt: expiresAt,
      user: user,
      canCancel: canCancel,
      isLoginSuccessful: isLoginSuccessful,
      intent: intent,
      messages: messages,
      remediations: remediations,
      authenticators: authenticators,
      token: token
    )
  }
  func toList() -> [Any?] {
    return [
      expiresAt,
      user,
      canCancel,
      isLoginSuccessful,
      intent.rawValue,
      messages,
      remediations,
      authenticators,
      token,
    ]
  }
}

private class HssOktaFlutterPluginApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return AuthenticationResult.fromList(self.readValue() as! [Any?])
    case 129:
      return DeviceAuthorizationSession.fromList(self.readValue() as! [Any?])
    case 130:
      return DirectAuthRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return IdxResponse.fromList(self.readValue() as! [Any?])
    case 132:
      return OktaToken.fromList(self.readValue() as! [Any?])
    case 133:
      return UserInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HssOktaFlutterPluginApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AuthenticationResult {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceAuthorizationSession {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DirectAuthRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? IdxResponse {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OktaToken {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? UserInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HssOktaFlutterPluginApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HssOktaFlutterPluginApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HssOktaFlutterPluginApiCodecWriter(data: data)
  }
}

class HssOktaFlutterPluginApiCodec: FlutterStandardMessageCodec {
  static let shared = HssOktaFlutterPluginApiCodec(readerWriter: HssOktaFlutterPluginApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HssOktaFlutterPluginApi {
  func startDirectAuthenticationFlow(request: DirectAuthRequest, completion: @escaping (Result<AuthenticationResult?, Error>) -> Void)
  func continueDirectAuthenticationMfaFlow(otp: String, completion: @escaping (Result<AuthenticationResult?, Error>) -> Void)
  func refreshDefaultToken(completion: @escaping (Result<Bool?, Error>) -> Void)
  func revokeDefaultToken(completion: @escaping (Result<Bool?, Error>) -> Void)
  func getCredential(completion: @escaping (Result<AuthenticationResult?, Error>) -> Void)
  func startDeviceAuthorizationFlow(completion: @escaping (Result<DeviceAuthorizationSession?, Error>) -> Void)
  func resumeDeviceAuthorizationFlow(completion: @escaping (Result<AuthenticationResult?, Error>) -> Void)
  func startTokenExchangeFlow(deviceSecret: String, idToken: String, completion: @escaping (Result<AuthenticationResult?, Error>) -> Void)
  func getAllUserIds(completion: @escaping (Result<[String], Error>) -> Void)
  func getToken(tokenId: String, completion: @escaping (Result<AuthenticationResult?, Error>) -> Void)
  func removeCredential(tokenId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func setDefaultToken(tokenId: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func authenticateWithEmailAndPassword(email: String, password: String, completion: @escaping (Result<IdxResponse?, Error>) -> Void)
  func startInteractionCodeFlow(email: String?, remidiation: String, completion: @escaping (Result<IdxResponse?, Error>) -> Void)
  func startSMSPhoneEnrollment(phoneNumber: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func continueSMSPhoneEnrollment(passcode: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func continueWithGoogleAuthenticator(code: String, completion: @escaping (Result<IdxResponse?, Error>) -> Void)
  func continueWithPasscode(passcode: String, completion: @escaping (Result<IdxResponse?, Error>) -> Void)
  func sendEmailCode(completion: @escaping (Result<Void, Error>) -> Void)
  func pollEmailCode(completion: @escaping (Result<IdxResponse?, Error>) -> Void)
  func recoverPassword(identifier: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func getIdxResponse(completion: @escaping (Result<IdxResponse?, Error>) -> Void)
  func cancelCurrentTransaction(completion: @escaping (Result<Bool, Error>) -> Void)
  func startUserEnrollmentFlow(email: String, details: [String: String], completion: @escaping (Result<Bool, Error>) -> Void)
  func getEnrollmentOptions(completion: @escaping (Result<String, Error>) -> Void)
  func enrollSecurityQuestion(questions: [String: String], completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HssOktaFlutterPluginApiSetup {
  /// The codec used by HssOktaFlutterPluginApi.
  static var codec: FlutterStandardMessageCodec { HssOktaFlutterPluginApiCodec.shared }
  /// Sets up an instance of `HssOktaFlutterPluginApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HssOktaFlutterPluginApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDirectAuthenticationFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.startDirectAuthenticationFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDirectAuthenticationFlowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DirectAuthRequest
        api.startDirectAuthenticationFlow(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDirectAuthenticationFlowChannel.setMessageHandler(nil)
    }
    let continueDirectAuthenticationMfaFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.continueDirectAuthenticationMfaFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      continueDirectAuthenticationMfaFlowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let otpArg = args[0] as! String
        api.continueDirectAuthenticationMfaFlow(otp: otpArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      continueDirectAuthenticationMfaFlowChannel.setMessageHandler(nil)
    }
    let refreshDefaultTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.refreshDefaultToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshDefaultTokenChannel.setMessageHandler { _, reply in
        api.refreshDefaultToken { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshDefaultTokenChannel.setMessageHandler(nil)
    }
    let revokeDefaultTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.revokeDefaultToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      revokeDefaultTokenChannel.setMessageHandler { _, reply in
        api.revokeDefaultToken { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      revokeDefaultTokenChannel.setMessageHandler(nil)
    }
    let getCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.getCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCredentialChannel.setMessageHandler { _, reply in
        api.getCredential { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCredentialChannel.setMessageHandler(nil)
    }
    let startDeviceAuthorizationFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.startDeviceAuthorizationFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDeviceAuthorizationFlowChannel.setMessageHandler { _, reply in
        api.startDeviceAuthorizationFlow { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDeviceAuthorizationFlowChannel.setMessageHandler(nil)
    }
    let resumeDeviceAuthorizationFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.resumeDeviceAuthorizationFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeDeviceAuthorizationFlowChannel.setMessageHandler { _, reply in
        api.resumeDeviceAuthorizationFlow { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resumeDeviceAuthorizationFlowChannel.setMessageHandler(nil)
    }
    let startTokenExchangeFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.startTokenExchangeFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startTokenExchangeFlowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceSecretArg = args[0] as! String
        let idTokenArg = args[1] as! String
        api.startTokenExchangeFlow(deviceSecret: deviceSecretArg, idToken: idTokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startTokenExchangeFlowChannel.setMessageHandler(nil)
    }
    let getAllUserIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.getAllUserIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAllUserIdsChannel.setMessageHandler { _, reply in
        api.getAllUserIds { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAllUserIdsChannel.setMessageHandler(nil)
    }
    let getTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.getToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenIdArg = args[0] as! String
        api.getToken(tokenId: tokenIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getTokenChannel.setMessageHandler(nil)
    }
    let removeCredentialChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.removeCredential\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeCredentialChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenIdArg = args[0] as! String
        api.removeCredential(tokenId: tokenIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      removeCredentialChannel.setMessageHandler(nil)
    }
    let setDefaultTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.setDefaultToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDefaultTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenIdArg = args[0] as! String
        api.setDefaultToken(tokenId: tokenIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setDefaultTokenChannel.setMessageHandler(nil)
    }
    let authenticateWithEmailAndPasswordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.authenticateWithEmailAndPassword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateWithEmailAndPasswordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let emailArg = args[0] as! String
        let passwordArg = args[1] as! String
        api.authenticateWithEmailAndPassword(email: emailArg, password: passwordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateWithEmailAndPasswordChannel.setMessageHandler(nil)
    }
    let startInteractionCodeFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.startInteractionCodeFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startInteractionCodeFlowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let emailArg: String? = nilOrValue(args[0])
        let remidiationArg = args[1] as! String
        api.startInteractionCodeFlow(email: emailArg, remidiation: remidiationArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startInteractionCodeFlowChannel.setMessageHandler(nil)
    }
    let startSMSPhoneEnrollmentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.startSMSPhoneEnrollment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSMSPhoneEnrollmentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let phoneNumberArg = args[0] as! String
        api.startSMSPhoneEnrollment(phoneNumber: phoneNumberArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startSMSPhoneEnrollmentChannel.setMessageHandler(nil)
    }
    let continueSMSPhoneEnrollmentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.continueSMSPhoneEnrollment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      continueSMSPhoneEnrollmentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let passcodeArg = args[0] as! String
        api.continueSMSPhoneEnrollment(passcode: passcodeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      continueSMSPhoneEnrollmentChannel.setMessageHandler(nil)
    }
    let continueWithGoogleAuthenticatorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.continueWithGoogleAuthenticator\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      continueWithGoogleAuthenticatorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let codeArg = args[0] as! String
        api.continueWithGoogleAuthenticator(code: codeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      continueWithGoogleAuthenticatorChannel.setMessageHandler(nil)
    }
    let continueWithPasscodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.continueWithPasscode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      continueWithPasscodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let passcodeArg = args[0] as! String
        api.continueWithPasscode(passcode: passcodeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      continueWithPasscodeChannel.setMessageHandler(nil)
    }
    let sendEmailCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.sendEmailCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendEmailCodeChannel.setMessageHandler { _, reply in
        api.sendEmailCode { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendEmailCodeChannel.setMessageHandler(nil)
    }
    let pollEmailCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.pollEmailCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pollEmailCodeChannel.setMessageHandler { _, reply in
        api.pollEmailCode { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pollEmailCodeChannel.setMessageHandler(nil)
    }
    let recoverPasswordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.recoverPassword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recoverPasswordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identifierArg = args[0] as! String
        api.recoverPassword(identifier: identifierArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recoverPasswordChannel.setMessageHandler(nil)
    }
    let getIdxResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.getIdxResponse\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIdxResponseChannel.setMessageHandler { _, reply in
        api.getIdxResponse { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getIdxResponseChannel.setMessageHandler(nil)
    }
    let cancelCurrentTransactionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.cancelCurrentTransaction\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelCurrentTransactionChannel.setMessageHandler { _, reply in
        api.cancelCurrentTransaction { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelCurrentTransactionChannel.setMessageHandler(nil)
    }
    let startUserEnrollmentFlowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.startUserEnrollmentFlow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startUserEnrollmentFlowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let emailArg = args[0] as! String
        let detailsArg = args[1] as! [String: String]
        api.startUserEnrollmentFlow(email: emailArg, details: detailsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startUserEnrollmentFlowChannel.setMessageHandler(nil)
    }
    let getEnrollmentOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.getEnrollmentOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getEnrollmentOptionsChannel.setMessageHandler { _, reply in
        api.getEnrollmentOptions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getEnrollmentOptionsChannel.setMessageHandler(nil)
    }
    let enrollSecurityQuestionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_flutter.HssOktaFlutterPluginApi.enrollSecurityQuestion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enrollSecurityQuestionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let questionsArg = args[0] as! [String: String]
        api.enrollSecurityQuestion(questions: questionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enrollSecurityQuestionChannel.setMessageHandler(nil)
    }
  }
}
