// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct HssOktaDirectAuthRequest {
  var username: String
  var password: String

  static func fromList(_ list: [Any?]) -> HssOktaDirectAuthRequest? {
    let username = list[0] as! String
    let password = list[1] as! String

    return HssOktaDirectAuthRequest(
      username: username,
      password: password
    )
  }
  func toList() -> [Any?] {
    return [
      username,
      password,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HssOktaDirectAuthResult {
  var success: Bool
  var error: String? = nil
  var id: String
  var token: String
  var issuedAt: Int64
  var tokenType: String
  var accessToken: String
  var scope: String
  var refreshToken: String

  static func fromList(_ list: [Any?]) -> HssOktaDirectAuthResult? {
    let success = list[0] as! Bool
    let error: String? = nilOrValue(list[1])
    let id = list[2] as! String
    let token = list[3] as! String
    let issuedAt = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)
    let tokenType = list[5] as! String
    let accessToken = list[6] as! String
    let scope = list[7] as! String
    let refreshToken = list[8] as! String

    return HssOktaDirectAuthResult(
      success: success,
      error: error,
      id: id,
      token: token,
      issuedAt: issuedAt,
      tokenType: tokenType,
      accessToken: accessToken,
      scope: scope,
      refreshToken: refreshToken
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      error,
      id,
      token,
      issuedAt,
      tokenType,
      accessToken,
      scope,
      refreshToken,
    ]
  }
}

private class HssOktaDirectAuthPluginApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return HssOktaDirectAuthRequest.fromList(self.readValue() as! [Any?])
      case 129:
        return HssOktaDirectAuthResult.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class HssOktaDirectAuthPluginApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HssOktaDirectAuthRequest {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? HssOktaDirectAuthResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HssOktaDirectAuthPluginApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HssOktaDirectAuthPluginApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HssOktaDirectAuthPluginApiCodecWriter(data: data)
  }
}

class HssOktaDirectAuthPluginApiCodec: FlutterStandardMessageCodec {
  static let shared = HssOktaDirectAuthPluginApiCodec(readerWriter: HssOktaDirectAuthPluginApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HssOktaDirectAuthPluginApi {
  func signInWithCredentials(request: HssOktaDirectAuthRequest, completion: @escaping (Result<HssOktaDirectAuthResult?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HssOktaDirectAuthPluginApiSetup {
  /// The codec used by HssOktaDirectAuthPluginApi.
  static var codec: FlutterStandardMessageCodec { HssOktaDirectAuthPluginApiCodec.shared }
  /// Sets up an instance of `HssOktaDirectAuthPluginApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HssOktaDirectAuthPluginApi?) {
    let signInWithCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hss_okta_direct_auth.HssOktaDirectAuthPluginApi.signInWithCredentials", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signInWithCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! HssOktaDirectAuthRequest
        api.signInWithCredentials(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      signInWithCredentialsChannel.setMessageHandler(nil)
    }
  }
}
