// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package dev.hypersense.software.hss_okta_direct_auth_plugin_api

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class DirectAuthResult(val raw: Int) {
  SUCCESS(0),
  MFAREQUIRED(1),
  ERROR(2);

  companion object {
    fun ofRaw(raw: Int): DirectAuthResult? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HssOktaDirectAuthRequest (
  val username: String,
  val password: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): HssOktaDirectAuthRequest {
      val username = list[0] as String
      val password = list[1] as String
      return HssOktaDirectAuthRequest(username, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      username,
      password,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HssOktaDirectAuthResult (
  val result: DirectAuthResult? = null,
  val error: String? = null,
  val id: String? = null,
  val token: String? = null,
  val issuedAt: Long? = null,
  val tokenType: String? = null,
  val accessToken: String? = null,
  val scope: String? = null,
  val refreshToken: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): HssOktaDirectAuthResult {
      val result: DirectAuthResult? = (list[0] as Int?)?.let {
        DirectAuthResult.ofRaw(it)
      }
      val error = list[1] as String?
      val id = list[2] as String?
      val token = list[3] as String?
      val issuedAt = list[4].let { if (it is Int) it.toLong() else it as Long? }
      val tokenType = list[5] as String?
      val accessToken = list[6] as String?
      val scope = list[7] as String?
      val refreshToken = list[8] as String?
      return HssOktaDirectAuthResult(result, error, id, token, issuedAt, tokenType, accessToken, scope, refreshToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      result?.raw,
      error,
      id,
      token,
      issuedAt,
      tokenType,
      accessToken,
      scope,
      refreshToken,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object HssOktaDirectAuthPluginApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HssOktaDirectAuthRequest.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HssOktaDirectAuthResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HssOktaDirectAuthRequest -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is HssOktaDirectAuthResult -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HssOktaDirectAuthPluginApi {
  fun init(clientid: String, signInRedirectUrl: String, signOutRedirectUrl: String, issuer: String, scopes: String)
  fun signInWithCredentials(request: HssOktaDirectAuthRequest, callback: (Result<HssOktaDirectAuthResult?>) -> Unit)
  fun mfaOtpSignInWithCredentials(otp: String, callback: (Result<HssOktaDirectAuthResult?>) -> Unit)
  fun refreshDefaultToken(callback: (Result<Boolean?>) -> Unit)
  fun revokeDefaultToken(callback: (Result<Boolean?>) -> Unit)
  fun getCredential(callback: (Result<HssOktaDirectAuthResult?>) -> Unit)

  companion object {
    /** The codec used by HssOktaDirectAuthPluginApi. */
    val codec: MessageCodec<Any?> by lazy {
      HssOktaDirectAuthPluginApiCodec
    }
    /** Sets up an instance of `HssOktaDirectAuthPluginApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: HssOktaDirectAuthPluginApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hss_okta_direct_auth.HssOktaDirectAuthPluginApi.init", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientidArg = args[0] as String
            val signInRedirectUrlArg = args[1] as String
            val signOutRedirectUrlArg = args[2] as String
            val issuerArg = args[3] as String
            val scopesArg = args[4] as String
            var wrapped: List<Any?>
            try {
              api.init(clientidArg, signInRedirectUrlArg, signOutRedirectUrlArg, issuerArg, scopesArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hss_okta_direct_auth.HssOktaDirectAuthPluginApi.signInWithCredentials", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as HssOktaDirectAuthRequest
            api.signInWithCredentials(requestArg) { result: Result<HssOktaDirectAuthResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hss_okta_direct_auth.HssOktaDirectAuthPluginApi.mfaOtpSignInWithCredentials", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val otpArg = args[0] as String
            api.mfaOtpSignInWithCredentials(otpArg) { result: Result<HssOktaDirectAuthResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hss_okta_direct_auth.HssOktaDirectAuthPluginApi.refreshDefaultToken", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshDefaultToken() { result: Result<Boolean?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hss_okta_direct_auth.HssOktaDirectAuthPluginApi.revokeDefaultToken", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.revokeDefaultToken() { result: Result<Boolean?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hss_okta_direct_auth.HssOktaDirectAuthPluginApi.getCredential", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCredential() { result: Result<HssOktaDirectAuthResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
